name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data visualization" >> report.md
          echo '![](feature_importance.png "Feature importance")' >> report.md
          echo '![](residuals.png "Residuals")' >> report.md

          cml comment create report.md